name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu

        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U kubsu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build --target test -t app-test .

      - name: Wait for PostgreSQL
        run: |
          sleep 10

      - name: Run tests
        run: |
          docker run --rm --network host app-test
