name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U kubsu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build --target test -t app-test .

      - name: Run tests
        run: docker run --rm app-test


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: wilbur
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e

            cd ~/tasks/docker
            git pull origin master

            podman build -t kubsu .

            podman rm -f kubsu || true

            podman run -d \
              --name kubsu \
              --network host \
              kubsu
