name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          set -e

          cd ~/tasks/docker

          echo "Pulling latest code..."
          git pull origin master

          echo "Building image..."
          podman build -t kubsu .

          echo "Stopping old container..."
          podman stop kubsu || true
          podman rm kubsu || true

          echo "Starting new container..."
          podman run -d \
            --name kubsu \
            --network host \
            --restart=always \
            kubsu

          echo "Waiting for app..."
          sleep 5

          curl -f http://127.0.0.1:8122/users/ || exit 1

          echo "DEPLOY SUCCESS"
